language: php
php:
  - '5.4'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm # on Trusty only
  - nightly
branches:
  only: "main"
before_install:
  - travis_retry composer self-update
  - composer install
script: phpunit --exclude-group FITS --bootstrap vendor/autoload.php tests